title: "Kavya Rao"
description: "Economist | Trade | M&E"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
author_profile: true

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

navigation:
  main: main

author:
  name: "Kavya Rao"
  avatar: "/kavya_formal.jpg"
  bio: ''

  minimal_mistakes_skin: default

defaults:
  - scope:
      path: ""
    values:
 include:
  - _pages
  
