title: "Kavya Rao"
description: "Economist | Policy Analyst | M&E"
url: "https://raokavya29.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

author_profile: true

author:
  name: ""
  avatar: "/kavya_formal.jpg"

defaults:
  - scope:
      path: ""
    values:
      layout: single
