remote_theme: minimal-mistakes-jekyll
plugins:
- jekyll-feed # add this line to the plugins list if you already have one
- jekyll-seo-tag
title: [Kavya Rao]
description: [Economist | M&E Professional]

