title: Kavya Rao
description: Economist | Policy Analyst | M&E
url: "https://raokavya29.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-include-cache
  - jekyll-feed

author:
  name: Kavya Rao
  avatar: /kavya_formal.jpg
