title: "Kavya Rao"
description: "Economist | Trade | M&E"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

navigation:
  main: main

author:
  name: "Kavya Rao"
  avatar: "/assets/kavya_formal.jpg"
  bio: "Economist | Trade | Public Finance"
